# Generated by Django 4.2.27 on 2026-03-23 10:34

from django.db import migrations

def rename_dns_forward(apps, schema_editor):
    PlaybookConfig = apps.get_model('playbooks_manager', 'PlaybookConfig')
    PlaybookConfig.objects.filter(name='Dns').update(name='DNS')

def rename_dns_backward(apps, schema_editor):
    PlaybookConfig = apps.get_model('playbooks_manager', 'PlaybookConfig')
    PlaybookConfig.objects.filter(name='DNS').update(name='Dns')

class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_manager', '0062_add_cleanbrowsing_to_free_to_use'),
    ]

    operations = [
        migrations.RunPython(rename_dns_forward, reverse_code=rename_dns_backward),
    ]